version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - hospital_scheduler_data:/app/hospital_scheduler_data
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
volumes:
  hospital_scheduler_data: 